version: "3.7"
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: school
      POSTGRES_PASSWORD: school
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
      - ../../data/dump:/db-dump
    ports:
      - 5432:5432

  redis:
    image: redis:6
    ports:
      - 6379:6379

  app:
    build:
      context: ../../
      dockerfile: ./ops-tools/docker/images/app/Dockerfile
    volumes:
      - ../../:/app
    ports:
      - 8888:8080
    depends_on:
      - db
      - redis
      