version: "3.7"

services:
  web:
    build:
      context: ./images/app/
      dockerfile: Dockerfile
    tty: true
    working_dir: /home/node/app
    command:  >
      sh -c "
        while ! nc -z db 5432;
        do
          echo sleeping;
          sleep 1;
        done;
        mv  /node_modules /home/node/app/node_modules; npm run migration:run; npm run start;
      "
    volumes:
      - ../../:/home/node/app
    ports:
      - 8888:8080
    networks:
      - docker-practice-net

  rds:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - docker-practice-net

  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: school
      POSTGRES_PASSWORD: school
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
      - ../../data/db-dump:/db-dump
    ports:
      - 5432:5432
    networks:
      - docker-practice-net

networks:
  docker-practice-net:
