version: '3.7'

volumes:
  postgres-data:

networks:
  docker-practice-net:
    name: docker-practice-net

services:
  web:
    build:
      context: ../../
      dockerfile: ops-tools/docker/images/app/Dockerfile
    volumes:
      - ../../:/usr/src/app
    ports:
      - 8888:8080
    depends_on:
      - redis
      - db
    command: >
      sh -c "
        while ! nc -vz db 5432;
        do
          sleep 1;
        done;

        npm run migration:run; npm run start;
      "
    networks:
      - docker-practice-net

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    networks:
      - docker-practice-net

  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: school
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../../data/dump:/db-dump
    ports:
      - 5432:5432
    networks:
      - docker-practice-net
