version: "3"
networks:
    docker-practice-net:

services:
    postgres_osipov:
        image: postgres:12.1
        restart: always
        ports:
            - "5432:5432"
        networks:
            - docker-practice-net
        volumes:
            - "../../data/postgres:/var/lib/postgresql/data"
            - "../../data/dump:/db-dump"
        environment:
            POSTGRES_PASSWORD: school
            POSTGRES_USER: postgres
            POSTGRES_DB: school
        container_name: osipov_postgr
    redis_osipov:
        image: redis:5.0.7
        restart: always
        ports:
            - "6379:6379"
        networks:
            - docker-practice-net
        container_name: osipov_redis
    app_osipov:
        build:
            context: ../..
            dockerfile: ./ops-tools/docker/images/app/Dockerfile
        restart: always
        ports:
            - "8888:8888"
        networks:
            - docker-practice-net
        volumes:
            - "../../:/app"
        container_name: osipov_app
        depends_on:
            - redis_osipov
            - postgres_osipov
            
        
        