version: "2.1"
services:
  db:
    image: postgres:12
    restart: always 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: school
      POSTGRES_PASSWORD: school
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
      - ../../data/dump:/db-dump
    ports:
      - 5432:5432
    networks:
      - docker-practice-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    ports:
      - 6379:6379
    networks:
      - docker-practice-net

  app:
    build:
      context: ../../
      dockerfile: ./ops-tools/docker/images/app/Dockerfile
    working_dir: /app
    command: bash -c "npm run migration:run && npm run start:dev"
    volumes:
      - ../../:/app
    ports:
      - 8888:8080
    depends_on:
      db:
        condition: service_healthy 
      redis:
        condition: service_started
    networks:
      - docker-practice-net

networks:
  docker-practice-net:
